### ISSUE TITLE
Where is deployMDHTToLocalMavenRepository.bat

### ISSUE THREAD

**Issue by LRFalk01** [bhits/document-validator#1]
Build docs reference a deployMDHTToLocalMavenRepository.bat file to deploy the required jar dependencies, but I am not finding this file anywhere. Am I crazy?

**Comment by CindyLiFei** [comment]
Please check on this release 1.0.0  page. 

https://github.com/bhits/document-validator/releases/tag/1.0.0

**Comment by LRFalk01** [comment]
Boom. Thanks !
